title: 11ty Subspace Builder
url: https://subspace-builder.nicholas.clooney.io

author:
  name: Nicholas Clooney
  email: not-gonna-tell-you@nicholas-clooney.simplelogin.com # 😉 You can still reach me.

theme:
  showSelectors: true
  rotatePreviews: true
  previewResetDelay: 200
  transitionDuration: 0.5s
   # all options: linear, ease, ease-in, ease-out, ease-in-out
  transitionTimingFunction: ease-in-out
  defaultId: sun

headerLinks:
  - label: GitHub
    url: https://github.com/TheClooneyCollection/11ty-subspace-builder
  - label: Nicholas's Blog
    url: https://blog.nicholas.clooney.io/
  - label: Mastodon
    url: https://mastodon.social/@NicholasClooney
    rel: me


# tracking with umami
umami:
  source: https://analytics.clooney.ninja/script.js
  id: 3bc809cb-ff21-4420-8636-99a8c7eecfed

# giscus comments system
# get your config here: https://giscus.app/
giscus:
  repo: TheClooneyCollection/11ty-subspace-builder
  repoId: R_kgDOOtI2Pw
  category: Announcements
  categoryId: DIC_kwDOOtI2P84CwAOl
  mapping: og:title
